app/routes.py
import tempfile
import logging
from flask import Blueprint, request, session
from flask import render_template, redirect, url_for, flash, send_file, make_response, jsonify
from flask_login import login_user, logout_user, login_required, current_user
import markdown
from weasyprint import HTML

from . import db, bcrypt, login_manager
from .models import User, UserDetails, Resumes
from .forms import LoginForm, RegistrationForm, ResumeForm
from src.generate_resume import get_resume_content, regenerate_resume_content


main_blueprint = Blueprint('main', __name__)
logger = logging.getLogger(__file__)
module_logger = logging.getLogger("fontTools")
module_logger.setLevel(logging.CRITICAL)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Check if user exists and the password is correct
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password_hash, form.password.data):
            login_user(user, remember=form.remember.data)
            # Redirect to the dashboard or other page
            return redirect(url_for('main.dashboard'))
        else:
            flash('Invalid username or password')
    return render_template('login.html', form=form)


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(username=form.username.data).first()
        if existing_user:
            flash('Username already exists')
            return redirect(url_for('main.register'))
        
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password_hash=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)


@main_blueprint.route('/dashboard')
@main_blueprint.route('/')
@login_required
def dashboard():
    return render_template('dashboard.html')


@main_blueprint.route('/generate', methods=['GET', 'POST'])
@login_required
def generate():
    user_details = UserDetails.query.filter_by(user_id=current_user.id).first()
    form = ResumeForm(obj=user_details)

    if form.validate_on_submit():

        if not user_details:
            user_details = UserDetails(user_id=current_user.id)
            db.session.add(user_details)

        form.populate_obj(user_details)
        db.session.commit()

        # Generate the resume content
        try:
            resume_content, resume_title = get_resume_content(form.data)
        except Exception as e:
            logger.error(f'🤬error with OPENAI API: {e}')
            return render_template('downtime.html')


        logger.info(f'User id🆔: {current_user.id}')
        resume = Resumes(
            user_id=current_user.id, job_description=form.data["job_description"],
            content=resume_content, summary=resume_title
            )
        db.session.add(resume)
        db.session.commit()
        generated_id = resume.id

        flash('Resume generated successfully.')
        # Redirect to the download route with the path of the temporary file
        return redirect(url_for('main.preview', resume_id=generated_id))

    return render_template('generate.html', form=form)


@main_blueprint.route('/preview/<int:resume_id>')
@login_required
def preview(resume_id):
    # Retrieve the resume content by ID
    resume = Resumes.query.get_or_404(resume_id)

    # Convert the Markdown content to HTML
    html_content = markdown.markdown(resume.content)
    logger.info(f'type of content from DB: {type(html_content)}')

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as temp:
        # Create a path for the temp file to send it
        HTML(string=html_content).write_pdf(temp.name)

    # Render the template with the filename
    return render_template('preview.html', resume_id=resume_id)


@main_blueprint.route('/pdf_preview/<int:resume_id>')
@login_required
def pdf_preview(resume_id):
    resume = Resumes.query.get_or_404(resume_id)

    html_content = markdown.markdown(resume.content)
    logger.info(f'type of content from DB: {type(html_content)}')

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as temp:
        temp_file_path = temp.name
        HTML(string=html_content).write_pdf(temp.name)

    return send_file(temp_file_path)


@main_blueprint.route('/download_resume/<int:resume_id>', methods=['GET'])
@login_required
def download_resume(resume_id):

    user_name = UserDetails.query.filter_by(user_id=current_user.id).first().full_name

    resume = Resumes.query.get_or_404(resume_id)

    # Convert the Markdown content to HTML
    html_content = markdown.markdown(resume.content)
    logger.info(f'type of content from DB: {type(html_content)}')

    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as temp:
        # Create a path for the temp file to send it
        temp_file_path = temp.name
        HTML(string=html_content).write_pdf(temp.name)

    # Render the template with the filename
    return make_response(
        send_file(
            temp_file_path,
            as_attachment=True,
            download_name=f"{user_name.replace(' ', '_').lower()}_resume_{resume_id}.pdf"
            ))


@main_blueprint.route('/feedback', methods=['POST'])
@login_required
def handle_feedback():
    logger.info("HANDLING FEEDBACK🔙")
    data = request.get_json()
    resume_id = data['resume_id']
    user_feedback = 1 if data['feedback'] == 'like' else 0

    # Find the resume and update feedback
    resume = Resumes.query.get_or_404(resume_id)
    resume.feedback = user_feedback
    
    # Commit the changes to the database
    db.session.commit()

    return jsonify({"message": "Feedback received"})


@main_blueprint.route('/regenerate/<int:resume_id>', methods=['POST'])
@login_required
def regenerate(resume_id:int):

    resume = Resumes.query.get_or_404(resume_id)
    user_data = UserDetails.query.get_or_404(current_user.id)
    user_data_dict = {c.name: getattr(user_data, c.name) for c in user_data.__table__.columns}
    new_resume_content = regenerate_resume_content(user_data_dict,
                                                   resume.content,
                                                   resume.job_description)
    resume.content = new_resume_content
    db.session.commit()

    flash('Resume generated successfully.')
    logger.info(f"Resume regenerated successfully🔥")
    return redirect(url_for('main.preview', resume_id=resume.id))



@main_blueprint.route('/archive')
@login_required
def archive():
    resume_list = Resumes.query.filter_by(user_id=current_user.id).order_by(Resumes.id.desc()).all()
    return render_template('archive.html', resume_list=resume_list)


@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.dashboard'))

app/templates/archive.html
{% extends "base.html" %}

{% block content %}
<div class="archive">
    <h2 class="div-center">Archiwum</h2>
    <ul class="resume-list">
        {% for resume in resume_list %}
            <li>
                <strong>Podsumownie:</strong> {{ resume.summary }}<br>
                <a href="{{ url_for('main.preview', resume_id=resume.id) }}">Zobacz CV</a>
            </li>
        {% else %}
            <li>Brak dostępnych CV.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/resgen_logo_no_bg.png') }}" type="image/icon type">
    <title>resgen.io</title>
</head>
<body>
    <div class="container">
        <a href="{{ url_for('main.dashboard') }}"  class="home-button btn">
            <!-- <img src="{{ url_for('static', filename='images/resgen_logo_no_bg.png') }}" height="14px"> -->
            Home
        </a>
        <img src="{{ url_for('static', filename='images/RESGEN_IO.png') }}" alt="Logo" class="logo">
    
        <div class="user-menu">
            <img src="{{ url_for('static', filename='images/user_icon.png') }}" alt="User Icon" class="user-icon">
            <a href="{{ url_for('main.logout') }}" class="logout-button btn">Wyloguj </a>
        </div>
    <!-- content goes here -->
    {% block content %}
    {% endblock %}
    </div>
    <footer>
        <div class="footer-content">
            <p>&copy; 2023 | Stefan Borek -- e/acc🚀 | Wrocław | LinkedIn: <a href="https://www.linkedin.com/company/100717764/admin/feed/posts/">resgen.io💜💚</a></p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

app/templates/dashboard.html
<!-- dashboard.html -->
{% extends "base.html" %}

    {% block content %}
        <form action="{{ url_for('main.generate') }}" method="post">
            <input class="btn" type="submit" value="Generuj CV">
        </form>
        <a class="btn" href="{{ url_for('main.archive') }}">Archiwum</a>
    {% endblock %}

app/templates/downtime.html
{% extends "base.html" %}
{% block content %}

    <h1>Uppss, we are down😞 try later.</h1>

{% endblock %}

app/templates/generate.html
{% extends "base.html" %}
{% block content %}
    <div class="user-data-block">
        <div class="data-form login-form custom-wide-form">
            <div id="generateForm" class="card body">
                <form  method="post" class="form-floating" onsubmit="showLoadingMessage()">
                    <h2 class="card-title text-center div-center">Generowanie CV</h2>

                    {{ form.hidden_tag() }}
                    
                    <div class="form-group">
                        <div class="form-group">
                            URL profilu LinkedIn (wymagane)
                        <span class="text-danger">
                        </span><br>
                            {{ form.linkedin_url(class="form-control wide-input", placeholder="www.linkedin.com/in/nazwa-użytkownika-886732123") }}
                    </div>
                    <div class="form-group">
                        {{ "Imię i Nazwisko (wymagane)" }}
                        <span class="text-danger"></span><br>
                        {{ form.full_name(class="form-control wide-input", placeholder="Imię i Nazwisko") }}
                        {% for error in form.full_name.errors %}
                            <small class="form-text text-muted">(wymagane)</small>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        Email (wymagane)
                        <span class="text-danger"></span><br>
                        {{ form.email(class="form-control wide-input", placeholder="twój.mail@mail.com") }}
                        {% for error in form.email.errors %}
                            <small class="form-text text-muted">(wymagane)</small>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        Numer telefonu (wymagane)
                        <span class="text-danger"></span><br>

                        {{ form.phone_number(class="form-control wide-input", placeholder="+00 123123123") }}
                        {% for error in form.phone_number.errors %}
                            <small class="form-text text-muted">(wymagane)</small>
                        {% endfor %}
                    </div>

                    <div class="form-group">
                        {{ "Github (opcjonalne)" }}
                        <span class="text-danger"></span><br>
                        {{ form.github(class="form-control wide-input", placeholder="github.com/username") }}
                    </div>

                    <div class="form-group">
                        Osobista witryna (opcjonalne)
                        <span class="text-danger"></span><br>
                        {{ form.personal_website(class="form-control wide-input", placeholder="www.twojadomena.pl") }}
                    </div>

                    <div class="form-group">
                        Twitter/X.com (opcjonalne)
                        <span class="text-danger"></span><br>
                        {{ form.twitter(class="form-control wide-input", placeholder="Twitter") }}
                    </div>

                    <div class="form-group">
                        Dodatkowe informacje (opcjonalne)<br>
                        <span class="text-danger"></span><br>
                        {{ form.additionals(class="form-control wide-input long-text-input", placeholder="Dodatkowe informacje - projekty, osiągnięcia, wolontariat etc.") }}
                        
                    </div>

                    <div class="form-group">
                        Opis stanowiska (wymagane)
                        <span class="text-danger"></span><br>
                        {{ form.job_description(class="form-control wide-input long-text-input", placeholder="Opis stanowiska pracy") }}
                        
                    </div>

                    <div class="div-center">
                        {{ form.submit(class="btn btn-primary btn-block") }}
                    </div>
                </form>

            </div>
        </div>
        <div id="loadingMessage" style="display: none;" class="form-ceter">
            <div class="loader">
                <img src="{{ url_for('static', filename='images/resgen_logo_no_bg.png') }}" width="123px">
            </div>
            <p>generujemy twoje <b>CV</b>📝</p>
        </div> 
    </div>
{% endblock %}

app/templates/login.html
<!-- register.html -->
{% extends "base.html" %}

{% block content %}
    <div class="form-ceter">
        <div class="login-form">
            <div class="card-body">
                <h2 class="card-title div-center">Zaloguj się</h2>
                <form action="/login" class="form-floating" method="POST">
                    {{ form.csrf_token }}
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.username(class="form-control", placeholder="Nazwa użytkownika") }}
                    </div>
                    <div class="form-group">
                        {{ form.password(class="form-control", placeholder="Hasło") }}
                    </div>
                    <div class="checkbox mb-3">
                        <label>
                            {{ form.remember }} Zapamiętaj mnie
                        </label>
                    </div>
                    <div class="div-center">
                        <button class="btn btn-primary btn-block form-ceter" type="submit">Zaloguj</button>
                    </div>
                </form>
            </div>
            <div class="card-footer form-ceter">
                Nie masz jeszcze konta? <a href="/register">Zarejestruj się</a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>regen.io</title>
</head>
<body>
    <div class="container">
        <img src="{{ url_for('static', filename='RESGEN_IO.png') }}" alt="Logo" class="logo">
        <h1>resgen.io</h1>
        <form method="post">
            <input class="btn" type="submit" value="Generate Resume">
        </form>
        <a class="btn" href="{{ url_for('archive') }}">View Archive</a>
    </div>
</body>
</html>

app/templates/preview.html
{% extends "base.html" %}

    {% block content %}
    <div id="preview" class="preview-div">
        <h1>Podgląd PDF</h1>
        <!-- Embed the PDF file for preview -->
        <iframe src="{{ url_for('main.pdf_preview', resume_id=resume_id) }}" width="600" height="500"></iframe>
        <br>
        <!-- Link to download the PDF file -->
        <a href="{{ url_for('main.download_resume', resume_id=resume_id) }}">Pobierz PDF</a>
        <h4>
            Co myślisz o tym CV?
            <button class="btn" onclick="sendFeedback('like', {{ resume_id }})">👍</button>
            <button class="btn" onclick="sendFeedback('dislike', {{ resume_id }})">👎</button>
        </h4>
        <p id="feedbackMessage"></p>
        <h4>
            Nie podoba Ci się?
            <br>
            <form id="generateForm" action="{{ url_for('main.regenerate', resume_id=resume_id) }}" method="post" onsubmit="showLoadingMessage()">
                <input class="btn" type="submit" value="Wygeneruj ponownie">
            </form>
        </h4>   
    </div>
    <div id="loadingMessage" style="display: none;" class="form-ceter">
        <div class="loader">
            <img src="{{ url_for('static', filename='images/resgen_logo_no_bg.png') }}" width="123px">
        </div>
        <p>Poprawiamy twoje <b>CV</b>📝</p>
    </div>
    {% endblock %}

app/templates/register.html
<!-- register.html -->
{% extends "base.html" %}

    {% block content %}
    <div class="row h-100 justify-content-center align-items-center">
        <div class="login-form">
            <div class="card-body">
                <h2 class="card-title div-center">Zarejestruj się</h2>
                <form action="/register" method="post" class="form-floating" aria-placeholder="Zarejestruj">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.username(class="form-control", id="username", placeholder="Nazwa użytkownika") }}
                    </div>
                    <div class="form-group">
                        {{ form.password(class="form-control", id="password", placeholder="Hasło") }}
                    </div>
                    <div class="form-group">
                        {{ form.confirm(class="form-control", id="confirm_password", placeholder="Powtórz Hasło") }}
                    </div>
                    <div class="checkbox mb-3">
                        <label>
                            {{ form.remember }} Zapamiętaj mnie
                        </label>
                    </div>
                    <div class="div-center">
                        {{ form.submit(class="btn btn-primary btn-block") }}
                    </div>
                </form>
            </div>

            <div class="card-footer text-center">
                Masz już konto? <a href="/login">Zaloguj</a>
            </div>
        </div>
    </div>
    {% endblock %}